### ISSUE TITLE
Suffix-Arrayでの破壊的変更

### ISSUE THREAD

**Issue by m1kit** [NASU41/AtCoderLibraryForJava#27]
SAのなかで元の配列を破壊的に変更しているが，結構厄介なバグの原因になるので適宜cloneするなりした方が良いかもしれないと思いました
https://github.com/NASU41/AtCoderLibraryForJava/blob/9e471432db4f785037fa9a54ee16fae24efa7687/StringAlgorithm/StringAlgorithm.java#L29

**Comment by uwi** [comment]
@m1kit 修正しました。確認お願いします。

**Comment by m1kit** [comment]
@uwi OKです．ありがとうございます🙇‍♂️
