### ISSUE TITLE
pow_mod で x が大きいとオーバーフローする

### ISSUE THREAD

**Issue by da-louis** [NASU41/AtCoderLibraryForJava#33]
Kotlin版へ移植( https://github.com/da-louis/ac-library-kt/pull/33 )してもらっている際に発見

`x`が大きいと30行目の`x*x`でオーバーフローしてしまうようなので、先にmodを取っておく必要がありそうです。
（もしくは第一引数は`int`型が正しい？）
https://github.com/NASU41/AtCoderLibraryForJava/blob/24160d880a5fc6d1caf9b95baa875e47fb568ef3/Math/MathLib.java#L25-L34

**Comment by uwi** [comment]
これm=1, n=0のときもおかしくなりますね

**Comment by m1kit** [comment]
`m=1e10`とかでもおかしくなるので，安全性と利便性とかを考えつつ検討した方がいいですね

**Comment by uwi** [comment]
@da-louis 修正しました。確認お願いします(もうマージされてるけど)

**Comment by da-louis** [comment]
バッチリそうです！ご対応ありがとうございます 🙏

**Comment by da-louis** [comment]
（あ、修正済みなので手癖でcloseしてしまいましたが必要だったらreopenして下さい…。。）
