### ISSUE TITLE
Self loop handling (in flow-problem library)

### ISSUE THREAD

**Issue by m1kit** [NASU41/AtCoderLibraryForJava#43]
https://github.com/atcoder/ac-library/issues/1 と同じ問題を抱えていそう

**Comment by uwi** [comment]
これは本家見守りですかね？ `from != to`のassertion入れるだけでもよさそうにみえるが

**Comment by NASU41** [comment]
本家 atcoder/ac-library#1 がclosedになっているらしい? 有識者の確認求む

**Comment by m1kit** [comment]
https://github.com/atcoder/ac-library/pull/12 これで修正されてる

**Comment by suisen-cp** [comment]
本家のコードをそのまま実装してプルリクを出しておきました (諸々の都合で実装が大幅に変更されました)

**Comment by suisen-cp** [comment]
Min Cost Flow も直しました．
