### ISSUE TITLE
LazySegTree: maxRight, minLeft の verify

### ISSUE THREAD

**Issue by suisen-cp** [NASU41/AtCoderLibraryForJava#48]
verify 用問題があれば教えていただけると有難いです．

**Comment by suisen-cp** [comment]
取り敢えず軽いテストを書いて PR を出しました．

**Comment by uwi** [comment]
https://beet-aizu.hatenablog.com/entry/2019/06/26/122933
とかどうですか？

**Comment by suisen-cp** [comment]
ありがとうございます！
